#define HOLE_FILLING_MODE @hole_filling_mode@

#define HOLE_FILLING_MODE_NONE       0
#define HOLE_FILLING_MODE_INPAINT    1
#define HOLE_FILLING_RUBBER_BAND_1   2
#define HOLE_FILLING_RUBBER_BAND_2   3
#define HOLE_FILLING_RUBBER_BAND_3   4
