#define BIT_IS_SURFACE    0

#define BIT_CONTINIOUS_T  1
#define BIT_CONTINIOUS_R  2
#define BIT_CONTINIOUS_B  3
#define BIT_CONTINIOUS_L  4

#define BIT_CONTINIOUS_TR 5
#define BIT_CONTINIOUS_TL 6
#define BIT_CONTINIOUS_BR 7
#define BIT_CONTINIOUS_BL 8

#define BIT_CURRENT_LEVEL 9

#define ALL_CONTINUITY_BITS 511