#define BIT_IS_SURFACE    0

#define BIT_CONTINUOUS_T  1
#define BIT_CONTINUOUS_R  2
#define BIT_CONTINUOUS_B  3
#define BIT_CONTINUOUS_L  4

#define BIT_CONTINUOUS_TR 5
#define BIT_CONTINUOUS_TL 6
#define BIT_CONTINUOUS_BR 7
#define BIT_CONTINUOUS_BL 8

#define BIT_CURRENT_LEVEL 9

#define ALL_CONTINUITY_BITS 511
