in vec3  gua_varying_world_position;
in vec3  gua_varying_normal;
in vec3  gua_varying_tangent;
in vec3  gua_varying_bitangent;
in vec2  gua_varying_texcoords;
in vec3  gua_varying_color;
in float gua_varying_roughness;
in float gua_varying_metalness;
in float gua_varying_emissivity;
