out vec3  gua_varying_position;
out vec3  gua_varying_normal;
out vec3  gua_varying_tangent;
out vec3  gua_varying_bitangent;
out vec2  gua_varying_texcoords;
out vec3  gua_varying_color;
out float gua_varying_roughness;
out float gua_varying_metalness;
out float gua_varying_emissivity;
